#!/bin/bash

# Freetype2
git clone git://git.sv.nongnu.org/freetype/freetype2.git freetype

# JBIG2dec
git clone git://git.ghostscript.com/jbig2dec.git jbig2dec

# IJG JPEG
# just download from www.ijg.org (version 8b, 16 May 2010)

# OpenJPEG
svn checkout http://openjpeg.googlecode.com/svn/trunk/ openjpeg

# muPDF
darcs get --lazy http://mupdf.com/repos/mupdf



