#!/bin/bash

# Freetype2
git clone git://git.sv.nongnu.org/freetype/freetype2.git freetype

# JBIG2dec
git clone git://git.ghostscript.com/jbig2dec.git jbig2dec

# IJG JPEG
wget http://www.ijg.org/files/jpegsrc.v8c.tar.gz
tar -xzf jpegsrc.v8c.tar.gz
mv jpeg-8c jpeg

# OpenJPEG
svn checkout http://openjpeg.googlecode.com/svn/trunk/ openjpeg

# muPDF
darcs get --lazy http://mupdf.com/repos/mupdf
