#!/bin/bash

# Get rid of old tarfile
rm -f dr-deps.tar.bz2

# Freetype2
cd freetype
git pull
cd ..

# JBIG2dec
cd jbig2dec
git pull
cd ..

# IJG JPEG
# just download from www.ijg.org (version 8b, 16 May 2010)

# OpenJPEG
cd openjpeg
svn up
cd ..

# muPDF
cd mupdf
darcs pull
cd ..

# Create tarfile
tar --exclude-backups --exclude-vcs -cjf dr-deps.tar.bz2 freetype jbig2dec jpeg mupdf openjpeg/libopenjpeg

# Update the droidreader directories, if a destination was entered
if [ "$1" != '' ]; then
   tar -C $1/jni -xvjf dr-deps.tar.bz2 
fi
