#!/bin/bash

# This file builds the native-code library, then the apk, and then installs
# the apk on a device (could be simulator) through adb. No device is specified,
# so the assumption is that there is only one device present.

rm -rf gen/de/hilses
ant clean

cd jni
ndk-build -B
cd -

ant debug
adb install -r bin/droidreader-debug.apk

